[package]
name = "dumb_saver_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
once_cell = "1"
num_cpus = "1"
threadpool = "1"
walkdir = "2"
rand = "0.8"
chrono = { version = "0.4", features = ["clock"] }
base64 = "0.21"
filetime = "0.2"
image = { version = "0.24", default-features = false, features = ["bmp", "png"] }
regex = "1"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = [
  "Win32_Foundation",
  "Win32_System_DataExchange",
  "Win32_System_Memory",
  "Win32_UI_Shell"
] }
